// Generated by CoffeeScript 1.7.1
(function() {
  var $, audio;

  $ = jQuery;

  $('body *').css({
    color: '#c00'
  });

  audio = document.createElement('audio');

  audio.src = 'assets/get-over-here.mp3';

  audio.addEventListener('canplay', function(event) {
    return event.target.play();
  }, false);

  $('body').append(audio);

}).call(this);
