// Generated by CoffeeScript 1.7.1
(function() {
  var EasterEgg, KeySequence, script;

  KeySequence = (function() {
    function KeySequence(maxKeys) {
      this.maxKeys = maxKeys != null ? maxKeys : 32;
      this.keys = [];
    }

    KeySequence.prototype.push = function(key) {
      var _results;
      this.keys.push(key);
      _results = [];
      while (this.keys.length > this.maxKeys) {
        _results.push(this.keys.shift());
      }
      return _results;
    };

    KeySequence.prototype.lastNKeys = function(n) {
      return this.keys.slice(this.keys.length - n, this.keys.length);
    };

    KeySequence.prototype.isMatch = function(seq) {
      var keys;
      keys = this.lastNKeys(seq.length);
      return keys.length === seq.length && keys.every(function(key, i) {
        return key === seq[i];
      });
    };

    return KeySequence;

  })();

  EasterEgg = (function() {
    var $, CODES;

    if (!$) {
      $ = null;
    }

    CODES = {
      KATAMARI: {
        CODE: [75, 65, 84, 65, 77, 65, 82, 73],
        SCRIPT: 'katamari'
      },
      KONAMI: {
        CODE: [38, 38, 40, 40, 37, 39, 37, 39, 66, 65],
        SCRIPT: 'game'
      },
      BLOOD: {
        CODE: [65, 66, 65, 67, 65, 66, 66],
        SCRIPT: 'blood'
      }
    };

    function EasterEgg() {
      $ = jQuery;
      this.keySequence = new KeySequence;
      $(document).keyup((function(_this) {
        return function(event) {
          if (window.DEBUG) {
            console.log(_this.keySequence.keys);
          }
          _this.keySequence.push(event.keyCode);
          return _this.checkCodes();
        };
      })(this));
    }

    EasterEgg.prototype.checkCodes = function() {
      var code, _results;
      _results = [];
      for (code in CODES) {
        if (this.keySequence.isMatch(CODES[code].CODE)) {
          _results.push(this.loadScript(CODES[code].SCRIPT));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    EasterEgg.prototype.loadScript = function(script) {
      return $('body').append($("<script src=lib/" + script + ".js></script>"));
    };

    return EasterEgg;

  })();

  if (typeof jQuery === "undefined" || jQuery === null) {
    script = document.createElement('script');
    script.src = '//code.jquery.com/jquery-2.1.1.min.js';
    script.onload = function() {
      return new EasterEgg;
    };
    document.querySelector('body').appendChild(script);
  }

}).call(this);
